// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUHL-uHRW4jE-X690zhoYfPdebgnKVwa8',
    appId: '1:784841383774:web:d2b865af6e3cd6bb0ff9cf',
    messagingSenderId: '784841383774',
    projectId: 'authentication-template-27fcb',
    authDomain: 'authentication-template-27fcb.firebaseapp.com',
    storageBucket: 'authentication-template-27fcb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA45I-CjzIlLGI8sWk7x5IGV8pzV5lNfkU',
    appId: '1:784841383774:android:b56e2af3cd9e1cf40ff9cf',
    messagingSenderId: '784841383774',
    projectId: 'authentication-template-27fcb',
    storageBucket: 'authentication-template-27fcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUWcu9eka-iOFJz-FPRH282HmhIUv_I5g',
    appId: '1:784841383774:ios:6d2f9bf5ff9dbefa0ff9cf',
    messagingSenderId: '784841383774',
    projectId: 'authentication-template-27fcb',
    storageBucket: 'authentication-template-27fcb.appspot.com',
    iosClientId: '784841383774-dpk8lh4er7qklu054pbf7kr09a6higj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUWcu9eka-iOFJz-FPRH282HmhIUv_I5g',
    appId: '1:784841383774:ios:6d2f9bf5ff9dbefa0ff9cf',
    messagingSenderId: '784841383774',
    projectId: 'authentication-template-27fcb',
    storageBucket: 'authentication-template-27fcb.appspot.com',
    iosClientId: '784841383774-dpk8lh4er7qklu054pbf7kr09a6higj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationTemplate',
  );
}
